version: 2.1

jobs:
  build:
    working_directory: ~/cookpad/streamy
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
    steps:
      - checkout
      - run:
          name: Configure & install Bundler
          command: gem install bundler
      - run:
          name: Bundle install
          command: 'bundle check || bundle install'
      - run:
          name: Test
          command: bundle exec rake
