name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
       fail-fast: false
       matrix:
         ruby:
           - 'head'
           - '3.1'
           - '3.0'
           - '2.7'
     continue-on-error: ${{ matrix.ruby == 'head' }}
     name: Ruby ${{ matrix.ruby }}
  
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: |
          bundle exec rake
